name: 'Run Docker Action'

inputs:
  docker-image:
    description: 'Image to pull'
    required: true

runs:
  using: "composite"
  steps:
    - name: Run Docker Image
      uses: docker://ghcr.io/tdupoiron-org/tdupoiron-org/demo-actions-docker:latest