name: 03 - BIS
run-name: 3 BIS

on:
  workflow_dispatch:

jobs:

  run-docker-action:
    runs-on: self-hosted
    steps:

      - name: Run Docker Action
        uses: docker://ghcr.io/tdupoiron-org/tdupoiron-org/demo-actions-docker
        with:
          args: "tom"

      # This use case is not supported because the action image is pulled from the ghcr at the beginning of the job
