name: 03 - Run Docker Action Docker Step
run-name: Run Docker Action Docker Step

on:
  workflow_dispatch:

jobs:

  run-docker-action:
    runs-on: ubuntu-latest
    steps:

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Action
        uses: docker://ghcr.io/tdupoiron-org/tdupoiron-org/demo-actions-docker:1709629510
        with:
          args: "tom"