name: 05 - Run Docker Composite
run-name: Run Docker Composite

on:
  workflow_dispatch:

jobs:

  run-docker-action:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Docker Composite
        uses: ./docker-composite
        with:
          docker-image: ghcr.io/tdupoiron-org/tdupoiron-org/demo-actions-docker