name: 06 - Run Before Script and Docker Step
run-name: Run Before Script and Docker Step

on:
  workflow_dispatch:

env:
  ACTIONS_RUNNER_HOOK_JOB_STARTED: /home/ec2-user/docker-login.sh
  ACTIONS_RUNNER_HOOK_JOB_COMPLETED: /home/ec2-user/docker-logout.sh

jobs:

  run-docker-action:
    runs-on: self-hosted
    steps:
    
      - name: Run Docker Action
        uses: docker://ghcr.io/tdupoiron-org/tdupoiron-org/demo-actions-docker:latest
        with:
          args: "tom"
