name: 06 - Run Before Script and Docker Step
run-name: Run Before Script and Docker Step

on:
  workflow_dispatch:

env:
  DOCKER_REGISTRY_USER: tdupoiron
  
jobs:

  run-docker-action:
    runs-on: self-hosted
    steps:
    
      - name: Run Docker Action
        uses: docker://ghcr.io/tdupoiron-org/tdupoiron-org/demo-actions-docker:latest
        with:
          args: "tom"
